version: "3.8"
services:
  telegram-chatbot:
    container_name: telegram-chatbot
    image: ghcr.io/spielhoelle/telegram_bot:latest
    environment: 
      - FLASK_APP=app.py
      - TELEGRAM_BOT_ID=${TELEGRAM_BOT_ID}
    ports:
      - "5000:5000"